### ISSUE TITLE
run finetune error

### ISSUE THREAD

**Issue by chinoll** [agiresearch/OpenAGI#17]
```
Traceback (most recent call last):
  File "/home/xxx/OpenAGI/finetune/flan_t5_finetune.py", line 188, in <module>
    train(args, logger)
  File "/home/xxx/OpenAGI/finetune/flan_t5_finetune.py", line 118, in train
    predicted_sequence, _ = generate_sequence(
  File "/home/xxx/OpenAGI/finetune/generate_trie.py", line 400, in generate_sequence
    output = model.generate_with_grad(
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/transformers/generation/utils.py", line 1474, in generate
    return self.beam_search(
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/transformers/generation/utils.py", line 2741, in beam_search
    next_token_scores_processed = logits_processor(input_ids, next_token_scores)
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/transformers/generation/logits_process.py", line 92, in __call__
    scores = processor(input_ids, scores)
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/transformers/generation/logits_process.py", line 691, in __call__
    mask[batch_id * self._num_beams + beam_id, self._prefix_allowed_tokens_fn(batch_id, sent)] = 0
  File "/home/xxx/OpenAGI/finetune/generate_trie.py", line 167, in prefix_allowed_tokens
    next_input_type = [
IndexError: list index out of range
```

**Comment by TobyGE** [comment]
I've fixed the bug and uploaded the new code. Please try again.
